pipeline:
  identifier: Build_demoJenkinsPipeline_1693982565544
  name: Build demoJenkinsPipeline
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: pradeepslkcoe/demoJenkinsPipeline
  stages:
    - parallel:
        - stage:
            name: Deploy
            identifier: Deploy
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: PowerShell
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo 'Deploying....'
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
        - stage:
            name: Trigger_Scripts
            identifier: Trigger_Scripts
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: Http
                      name: Http_1
                      identifier: Http_1
                      spec:
                        url: https://httpbin.org/get
                        method: GET
                        headers: []
                        inputVariables: []
                        outputVariables: []
                      timeout: 10s
            tags: {}
